name: 'Run Bot - Morning Schedule (10 Iterations)'

on:
  workflow_dispatch:  # به شما اجازه اجرای دستی را هم می‌دهد
  schedule:
    # در ساعت 2:30 بامداد UTC اجرا می‌شود که معادل 6:00 صبح ایران است
    - cron: '30 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install web3 requests py-solc-x eth-hash eth-abi

      - name: Run the main script for Morning
        env:
          MY_PRIVATE_KEY: ${{ secrets.MY_PRIVATE_KEY }}
          NUM_ITERATIONS: '5' # اجرای صبح با ۱۰ تکرار
        run: python main.py
